# Generated by Django 5.1.4 on 2025-01-15 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReportedIncident',
            fields=[
                ('incident_id', models.AutoField(primary_key=True, serialize=False)),
                ('incident_type', models.CharField(max_length=255)),
                ('incident_location', models.CharField(max_length=255)),
                ('incident_lat', models.FloatField()),
                ('incident_long', models.FloatField()),
                ('incident_timestamp', models.DateTimeField()),
                ('incident_vehicle_vin', models.CharField(max_length=255)),
                ('incident_image', models.ImageField(upload_to='images/')),
                ('incident_owner_metadata', models.JSONField()),
                ('incident_camera_metadata', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='RTOCenter',
            fields=[
                ('rto_id', models.AutoField(primary_key=True, serialize=False)),
                ('rto_username', models.CharField(max_length=255)),
                ('rto_password', models.CharField(max_length=255)),
                ('rto_name', models.CharField(max_length=255)),
                ('rto_location', models.CharField(max_length=255)),
                ('rto_lat', models.FloatField()),
                ('rto_long', models.FloatField()),
                ('rto_report_to_mails', models.JSONField()),
                ('rto_metadata', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='ReportedIncidentChallan',
            fields=[
                ('challan_id', models.AutoField(primary_key=True, serialize=False)),
                ('challan_amount', models.FloatField()),
                ('challan_timestamp', models.DateTimeField()),
                ('challan_status', models.BooleanField()),
                ('challan_payment_timestamp', models.DateTimeField()),
                ('challan_payment_status', models.BooleanField()),
                ('challan_payment_reference', models.CharField(max_length=255)),
                ('challan_payment_amount', models.FloatField()),
                ('challan_payment_mode', models.CharField(max_length=255)),
                ('challan_payment_receipt', models.ImageField(upload_to='images/')),
                ('challan_payment_metadata', models.JSONField()),
                ('incident_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.reportedincident')),
            ],
        ),
    ]
