# Generated by Django 4.2.18 on 2025-01-16 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('vehicle_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('vehicle_vin', models.CharField(max_length=255, unique=True)),
                ('vehicle_owner_name', models.CharField(max_length=255, null=True)),
                ('vehicle_owner_address', models.CharField(max_length=255, null=True)),
                ('vehicle_owner_contact', models.CharField(max_length=15, null=True)),
                ('vehicle_metadata', models.JSONField(default=dict)),
            ],
        ),
        migrations.AddField(
            model_name='reportedincident',
            name='incident_vehicle_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reportedincidentchallan',
            name='vehicle_id',
            field=models.IntegerField(default=0),
        ),
    ]
