# Generated by Django 5.1.4 on 2025-01-15 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rtocenter_groups_rtocenter_is_superuser_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportedincident',
            name='incident_vehicle_vin',
        ),
        migrations.RemoveField(
            model_name='reportedincidentchallan',
            name='challan_payment_reference',
        ),
        migrations.RemoveField(
            model_name='reportedincidentchallan',
            name='challan_payment_status',
        ),
        migrations.RemoveField(
            model_name='reportedincidentchallan',
            name='challan_status',
        ),
        migrations.AddField(
            model_name='reportedincident',
            name='incident_vin',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='reportedincidentchallan',
            name='challan_payment_reference_id',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='reportedincidentchallan',
            name='challan_status_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='reportedincident',
            name='incident_camera_metadata',
            field=models.JSONField(default={}),
        ),
        migrations.AlterField(
            model_name='reportedincident',
            name='incident_owner_metadata',
            field=models.JSONField(default={}),
        ),
        migrations.AlterField(
            model_name='reportedincidentchallan',
            name='challan_payment_metadata',
            field=models.JSONField(default={}),
        ),
        migrations.AlterField(
            model_name='reportedincidentchallan',
            name='challan_payment_mode',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='reportedincidentchallan',
            name='challan_payment_receipt',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='reportedincidentchallan',
            name='challan_payment_timestamp',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='reportedincidentchallan',
            name='challan_timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
