# Generated by Django 5.1.4 on 2025-01-15 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_reportedincident_incident_vehicle_vin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportedincident',
            name='incident_camera_metadata',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='reportedincident',
            name='incident_owner_metadata',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='reportedincidentchallan',
            name='challan_payment_metadata',
            field=models.JSONField(default=dict),
        ),
    ]
